version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  data:
