# Use an official Node.js runtime as a parent image
FROM node:22-slim

# Install AWS CLI
RUN apt-get update && apt-get install -y awscli

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install AWS CDK globally
RUN npm install -g aws-cdk

# Copy package.json and package-lock.json to the working directory
COPY cdk/package*.json ./

# Install the necessary dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY cdk/ ./

# Set the entry point to run the CDK deployment command
ENTRYPOINT ["sh", "-c", "aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $AWS_REGION && cdk deploy --require-approval never"]
