name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: |
        # Create .env.local file
        # Define the file name
        file=".env.local"
        
        # Write the environment variables to the file
        cat <<EOL > $file
        DB_HOST=localhost
        DB_USER=volaka
        DB_PASSWORD=volaka_password
        DB_NAME=volaka
        DB_PORT=5432
        PORT=8080
        POSTGRES_USER=volaka
        POSTGRES_PASSWORD=volaka_password
        POSTGRES_DB=volaka
        EOL
        
        # Run the test database
        docker-compose -f docker-compose-local-db.yml up -d
        go test ./...

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Amazon ECR "Login" Action for GitHub Actions
      uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{github.repository}}:${{ github.sha }}
